// Mocks generated by Mockito 5.4.6 from annotations
// in nolatech_messenger/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:nolatech_messenger/core/errors/failure.dart' as _i5;
import 'package:nolatech_messenger/domain/entities/conversation.dart' as _i8;
import 'package:nolatech_messenger/domain/entities/message.dart' as _i9;
import 'package:nolatech_messenger/domain/entities/user.dart' as _i6;
import 'package:nolatech_messenger/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:nolatech_messenger/domain/repositories/chat_repository.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> register(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [name, email, password]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>(
                this,
                Invocation.method(#register, [name, email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> getUserData(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, [uid]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither_0<_i5.Failure, _i6.User>(
                this,
                Invocation.method(#getUserData, [uid]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.User>>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i7.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i8.Conversation>> getUserConversations(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserConversations, [userId]),
            returnValue: _i4.Stream<List<_i8.Conversation>>.empty(),
          )
          as _i4.Stream<List<_i8.Conversation>>);

  @override
  _i4.Stream<List<_i9.Message>> getMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [chatId]),
            returnValue: _i4.Stream<List<_i9.Message>>.empty(),
          )
          as _i4.Stream<List<_i9.Message>>);

  @override
  _i4.Future<void> sendMessage(String? chatId, _i9.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [chatId, message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markMessagesAsRead(String? chatId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessagesAsRead, [chatId, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createChatIfNotExists(
    String? chatId,
    List<String>? participantIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createChatIfNotExists, [chatId, participantIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.User>> fetchAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllUsers, []),
            returnValue: _i4.Future<List<_i6.User>>.value(<_i6.User>[]),
          )
          as _i4.Future<List<_i6.User>>);

  @override
  _i4.Future<String> createOrGetChat(String? userAId, String? userBId) =>
      (super.noSuchMethod(
            Invocation.method(#createOrGetChat, [userAId, userBId]),
            returnValue: _i4.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createOrGetChat, [userAId, userBId]),
              ),
            ),
          )
          as _i4.Future<String>);
}
